[custom]
;推荐订阅更新时间 1天=24小时=1440分钟=86400秒
;2天=48小时=2880分钟=172800秒
;3天=72小时=4320分钟=259200秒
;7天=168小时=10080分钟=604800秒

;https://amyconvert.com/api?target=quanx&url=https%3A%2F%2Fgist.githubusercontent.com%2Floongfzs%2Fd6db70055f33125f7834cf3b432afee5%2Fraw%2F2c7326791402a152c7354278904f1a54eb73c7ed%2Fcnix.211224.yaml&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2Floongfzs%2FQuantumultX-Config%2Fmain%2FConfig%2Fmain.ini&emoji=true&list=false&tfo=true&scv=false&fdn=false&sort=false&udp=true

;设置规则标志位
ruleset=DIRECT,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/LocalAreaNetwork.list
ruleset=DIRECT,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Directly1.list
ruleset=🎬 奈飞视频,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Big.list
;ruleset=📀 串流媒体,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Big.list
ruleset=✅ 节点选择,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Nodeselect1.list
;ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=REJECT,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Alwaysreject.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Prohibitconnect.list
;  广告拦截
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
;ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
; 禁止使用WIFi万能钥匙
;ruleset=🛑 广告拦截,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/WiFiMaster.list
; 电信运营商
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/ChinaMobile.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/ChinaUnicom.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/ChinaTelecom.list
# CN
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=DIRECT,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/WeChat.list
;ruleset=📶 微信聊天,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/WeChat.list
# 地区分流专用
ruleset=DIRECT,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/CN.list
ruleset=🇨🇳 台湾节点,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/TWOnly.list
ruleset=🇯🇵 日本节点,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/JPOnly.list
ruleset=🇸🇬 狮城节点,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/SGOnly.list
ruleset=🇭🇰 香港节点,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/HKOnly.list
ruleset=🇺🇸 美国节点,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/USOnly.list
ruleset=🇺🇳 全球节点,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/GLOBAL.All.list
; 游戏平台
;ruleset=🎮 游戏平台,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/commongames.list
;ruleset=🎮 游戏平台,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Game/Nintendo.list
;ruleset=🎮 游戏平台,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Game/EA.list
; onedrive分流，必须排在微软服务前面
;ruleset=Ⓜ️ 微软云盘,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
; Apple
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AppleTV.list
;ruleset=🍎 苹果服务,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Apple/AppleMedia.list
;ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Apple.list
; TG
;ruleset=🛰️ 即时通信,https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Telegram.list
ruleset=🛰️ 即时通信,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/TelegramIP.list
; 奈飞视频，大流量下载
ruleset=🎬 奈飞视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
; 高大全
;ruleset=🎬 奈飞视频,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/Netflix.list
;ruleset=🎬 奈飞视频,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/Spotify.list
; 国外媒体
; 新
;ruleset=📀 串流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
; 高大全
;ruleset=📀 串流媒体,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/Netflix.list
ruleset=📀 串流媒体,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/Spotify.list
ruleset=🇯🇵 日本节点,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Dmm.list
ruleset=📀 串流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/DisneyPlus.list
;ruleset=📀 串流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Hulu.list
;ruleset=📀 串流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/HuluJapan.list
ruleset=📀 串流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/HBO.list
;ruleset=📀 串流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/HBO_GO_HKG.list
ruleset=📀 串流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SoundCloud.list
ruleset=📀 串流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TikTok.list
;ruleset=📀 串流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/DAZN.list
;ruleset=📀 串流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/HWTV.list
;ruleset=📀 串流媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/KKTV.list
ruleset=🇺🇳 全球节点,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BBC.list
;
;ruleset=📺 巴哈姆特,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
;ruleset=📺 巴哈姆特,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TaiWanGood.list
;
ruleset=📺 奇艺哔哩,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/BiliBili.list
ruleset=📺 奇艺哔哩,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/iQIYI.list
;ruleset=📺 奇艺哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Iqiyi.list
;ruleset=📺 奇艺哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/IqiyiHMT.list
;ruleset=📺 奇艺哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
;ruleset=📺 奇艺哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
; 国外代理
; Google
ruleset=✅ 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTubeMusic.list
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleEarth.list
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
; Microsoft
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Microsoft.list
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Github.list
;media
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Porn.list
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Pornhub.list
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Twitch.list
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Wikimedia.list
; tools
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Developer.list
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TeraBox.list
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Apkpure.list
; social
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Facebook.list
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/KakaoTalk.list
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Instagram.list
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Reddit.list
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Twitter.list
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Whatsapp.list
; news
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Pixiv.list
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Scholar.list
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Wikipedia.list
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/NYTimes.list
;  Global
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Spark.list
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/source/rule/Synology/Synology.list
;
;ruleset=✅ 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TopBlockedSites.list
ruleset=✅ 节点选择,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Nodeselect2.list
; 直连
;国内媒体
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/Youku%26Tudou.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEase.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/CCTV.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/DouYu.list
;ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/PPTVPPLive.list
;ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Meitu.list
;ruleset=DIRECT,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/KuaiShou.list
ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/XiMaLaYa.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/MGTVTV.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/DiDi.list
ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/AcFun.list
ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/LeTV.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/Kugou%26Kuwo.list
;ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YYeTs.list
;购物平台
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/PDD.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/JingDong.list
ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/MeiTuan.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/FeiZhu.list
; 新闻资讯
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sina.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/ByteDance.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/ChinaNews.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/FengHuangWang.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/Sohu.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/DouBan.list
; 教育学习
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/CNKI.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/CSDN.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/YuanFuDao.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/17zuoye.list
; 工具网站
;ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Xunlei.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Baidu.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AccelerateDirectSites.list
;ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/360.list
;ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/58.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/4399.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/DingTalk.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/12306.list
ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/115.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/58TongCheng.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Blued.list
ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/ChengTongWangPan.list
ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/Keep.list
ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/JianGuoYun.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/LuDaShi.list
ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/iFlytek.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TeamViewer.list
; 公共直连
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/PublicDirectCDN.list
;ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/PrivateTracker.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Tencent.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Alibaba.list
ruleset=DIRECT,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Directly2.list
;ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
; 银行金融
; 邮政储蓄
ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/PSBC.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/ICBC.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/AliPay.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/CCB.list
; 光大银行
ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/CEB.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/UnionPay.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/VISA.list
ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/ABC.list
; 交通银行
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/BOCOM.list
; 中国银行
ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/BOC.list
; 广发银行 
ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/CGB.list
; 招商银行
ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/CMB.list
; 中信银行
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/CITIC.list
; 手机厂商
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/HuaWei.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/Xiaomi.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/OnePlus.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/OPPO.list
;ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/Vivo.list
; 中国ip，选择性启用
;ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
; 下载
;ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=DIRECT,[]GEOIP,CN
ruleset=✅ 节点选择,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🇭🇰 香港节点`select`(香港|HKG)

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/GeneralConfig_no-ipv6_redir-host.yml
